#
# This configmap is used by the all tree policies
# and specifies the configuration required to install velero, backup or restore
#
# This config is set to use snapshotVolumes for backing up PVs; this option works only if 
# your backup and restore clusters use the same StorageClass 
# and the restore cluster can access the region/location where the volume snapshot are stored
# 
apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
data:
  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: acm-app-backup 
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator

# define cloud-credential used to connect to the storage location, base64 encoded string
# for example, for an aws storage location, the credential is in this format
#
# [default]
# aws_access_key_id=<id>
# aws_secret_access_key=<key>
#
  dpa.aws.backup.cloud.credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPTxpZD4KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PTxrZXk+


## DPA resource configuration
#
  #DPA resource name; use the same name for all hubs, the PV cannot be restored if 
  # the BackupStorageLocation resource doesn't have the same name
  # on both backup and restore cluster 
  dpaName: dpa
  backup.volumeSnapshotLocation: dpa-1
  dpa.backup.cloud.credentials.name: cloud-credentials
#######
# DPA spec
# below is the spec format for an aws storage
# update this with the DPA format for the type of storage you are using
# values specified with brackets <> should be updated before applying this configmap
  dpa.spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"<us-east-1>\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"<dpa.backup.cloud.credentials.name>\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"<bucket-name>\",
          \"prefix\": \"<in-bucket-folder-name>\"
        },
        \"provider\": \"<aws>\"
      }
    }
  ],
  \"configuration\": {
    \"restic\": {
      \"enable\": false
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"openshift\",
        \"aws\"
      ],
      \"podConfig\": {
        \"resourceAllocations\": {
          \"limits\": {
            \"cpu\": \"2\",
            \"memory\": \"1Gi\"
          },
          \"requests\": {
            \"cpu\": \"500m\",
            \"memory\": \"256Mi\"
          }
        }
      }
    }
  },
  \"snapshotLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"<use here ClusterClaim region.open-cluster-management.io value>\"
        },
        \"provider\": \"<aws>\"
      }
    },
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"<east1>\",
          \"region\": \"<us-east-1>\"
        },
        \"provider\": \"<aws>\"
      }
    },
  ]
}"
## END DPA ##

###### End Configuration for the oadp-hdr-install policy ###
###########################################################

### Configuration for the oadp-hdr-backup policy
################################################
  # the name prefix for the resource to backup
  backup.prefix: acm-pv

  backup.snapshotVolumes: "true"
  backup.defaultVolumesToRestic: "false"
  backup.volumeSnapshotLocation: dpa-1

  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s

  # list here all applications namespaces you want to backup
  # for example backup.nsToBackup: "[\"pacman-ns\", \"helloworld-pv-ns\"]"
  backup.nsToBackup: "[\"app1-ns\", \"app2-ns\", \"app3-ns\"]" 

  # resources to be excluded from backup; if empty, all resources from the specified namespace are included
  backup.excludedResources: "[]"

###### End Configuration for the oadp-hdr-backup policy ###
###########################################################

###### Configuration for the oadp-hdr-restore policy ###
####################################
  # list here all apps ns you do now want to restore from the specified backup
  # if empty, all namespaces in thi backup are restored
  # for example backup.nsToBackup: "[\"box-ns\"]"
  restore.nsToExcludeFromRestore: "[]"

## restore storage class mapping ##
  restore.storage.config.name: storage-class-acm-app
  restore.storage.config.mappings: "{
          \"managed-csi\": \"thin\",
    }"
###### End Configuration for the oadp-hdr-restore policy ###
###########################################################

