apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: demo-stable-policies-chan
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management-io/policy-collection.git
