apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: terminating-configpolicies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: terminating-configpolicies
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - "{{hub .ManagedClusterName hub}}"
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: policy.open-cluster-management.io/v1
                kind: ConfigurationPolicy
                status:
                  compliant: Terminating
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: terminating-configpolicies-placement
  namespace: default
placementRef:
  name: terminating-configpolicies-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: terminating-configpolicies
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: terminating-configpolicies-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
  clusterConditions: []
