apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-group
  namespace: rhacs-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
data: '{{hub copySecretData "policies" "admission-control-tls" hub}}'
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data: '{{hub copySecretData "policies" "collector-tls" hub}}'
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data: '{{hub copySecretData "policies" "sensor-tls" hub}}'
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
type: Opaque
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
spec:
  clusterName: '{{hub .ManagedClusterName hub}}'
  auditLogs:
    collection: Auto
  centralEndpoint: '{{hub fromConfigMap "" "acs-config" "acs-host" hub}}'
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
