apiVersion: v1
kind: ConfigMap
metadata:
  name: opp-settings
  namespace: policies
data:
  vmwareReplicas: "6"
  vmwareCPU: "8"
  vmwareMemory: "32768" 
  awsReplicas: "2"
  awsInstanceType: m6a.2xlarge
  us-east-1-4.12: ami-0c321aac14de997e3
  us-east-2-4.12: ami-0fce6015e3592d4a5
  us-east-1-4.13: ami-03efc0188afd5f5b9
  us-east-2-4.13: ami-031d6e5e3d4f2f192
  us-east-1-4.14: ami-058af1563befa5c0e
  us-east-2-4.14: ami-0dd810c1f47c5c233
  us-east-1-4.15: ami-0d653d86d4113326a
  us-east-2-4.15: ami-0d6c4efce8daf7d2d
  us-east-1-4.16: ami-03ca8605aa130b597
  us-east-2-4.16: ami-09ab4b62c2f0a4555
  us-east-1-4.17: ami-0eddfa7634d2beba0
  us-east-2-4.17: ami-022fbb77a3226215f
  us-east-1-4.18: ami-08f1807771f4e468b
  us-east-2-4.18: ami-078e26f293629fe91
  us-east-1-4.19: ami-04025e24e1e0ef752
  us-east-2-4.19: ami-0bd7465e9989694c9
  zone1: a
  zone2: b
  zone3: c
